# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: smart-iot-app
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
  # stage: dev
  stage: dev
  region: ap-southeast-1

# environment
  environment:
    FARM_TABLE: 
      Ref: FarmDynamoDbTable
    FARM_USER_TABLE:
      Ref: FarmUserDynamoDbTable
    FARM_DEVICE_TABLE:
      Ref: FarmDevicesDynamoDbTable


# you can add statements to the Lambda function's IAM Role here
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource:
            Fn::Join:
              - ""
              - - "arn:aws:s3:::"
                - "Ref" : "ServerlessDeploymentBucket"
                - "/*"
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:CreateTable
            - dynamodb:DeleteItem
          Resource: 
            - "Fn::GetAtt": [FarmDynamoDbTable, Arn]
            - "Fn::GetAtt": [FarmUserDynamoDbTable, Arn]
            - "Fn::GetAtt": [FarmDevicesDynamoDbTable, Arn]

# you can add packaging information here
package:
  patterns:
    - '!**'
    - handler.js
    - node_modules/uuid
    - node_modules/bluebird
    - serverless/TableFunctions/handler.js

functions:
#  hello:
#    handler: handler.hello
  getFarmExample:
    handler: handler.getFarmExample
    events:
      - http:
          path: /farm/get/example
          method: GET
          cors: true
  getFarmList:
    handler: handler.getFarmList
    description: List all farms
    events:
      - http:
          path: /farm/list/all
          method: GET
          cors: true
  getFarmByID:
    handler: handler.getFarmByID
    description: Get a farm data by farm's ID
    events:
      - http:
          path: /farm/get/{ID}
          method: GET
          cors: true
  createFarm:
    handler: handler.createFarm
    description: Send a farm information
    events:
      - http:
          path: /farm/create
          method: POST
          cors: true
  createUser:
    handler: handler.createUser
    description: Send a user information with username and list of farms
    events:
      - http:
          path: /user/create
          method: POST
          cors: 
            origin: "https://project-three-dun.vercel.app/"
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  createUserToTable:
    handler: handler.createUserToTable
    description: Use by lambda trigger only.
    events:
      - http:
          path: /trigger/createUser
          method: POST
  getUserList:
    handler: handler.getUserList
    description: Return a list of users with id
    events:
      - http:
          path: /user/list/all
          method: GET
          cors: true
  getUserByID:
    handler: handler.getUserByID
    description: Get a data of user by given ID
    events:
      - http:
          path: /user/get/{ID}
          method: GET
          cors: true
  registerDevice:
    handler: handler.registerDevice
    description: Use for first time register of new device.
    events:
      - http:
          path: /device/register
          method: POST
          cors: true
  getDeviceByID:
    handler: handler.getDeviceByID
    description: Get device by given ID.
    events:
      - http:
          path: /device/in/{ID}
          method: GET
          cors: true
  getAllDevices:
    handler: handler.getAllDevices
    description: Get all devices.
    events: 
      - http:
          path: /device/all
          method: GET
          cors: true
  getDevicesByFarmName:
    handler: handler.getDevicesByFarmName
    description: Get devices of target farm
    events:
      - http:
          path: /device/getByFarm
          method: POST
  liveDataHandler:
    handler: handler.liveDataHandler
    description: handle a request from topic and send back to application
    events:
      - http:
          path: /liveData
          method: POST
          cors: true
  createFarmAsTable:
    handler: handler.createFarmAsTable
    description: (For web only!) Create a farm table which used for logging live data for each device.
    events:
      - http:
          path: /farm/create_as_table
          method: POST
          cors: true
  writeDataFromIOT:
    handler: handler.writeDataFromIOT
    description: Handle write and update of value from iot device in the farm table
    events:
      - http:
          path: /farm/write
          method: POST
  changeDeviceStatusByMobile:
    handler: handler.changeDeviceStatusByMobile
    description: To control state of device from mobile application, topics{For app use 'farmName/device/change_state', For device use 'farmName/device/state/listen/request'}
    events:
      - http:
          path: /farm/device/changeState
          method: POST
  updateValue:
    handler: serverless/TableFunctions/handler.updateValue
    description: Update value(s) of one table.
    events:
      - http:
          path: /any/targetTable/update
          method: POST
          cors: true
  deleteValue:
    handler: serverless/TableFunctions/handler.deleteValue
    description: Delete value(s) of one table
    events:
      - http:
          path: /any/targetTable/delete
          method: POST
          cors: true
  sendControlValue:
    handler: handler.sendControlValue
    description: Send a value to control the device
    events:
      - http:
          path: /farm/device/controlValue
          method: POST

resources:
  Resources:
    FarmDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          # - AttributeName: Name
          #   AttributeType: S
          - AttributeName: "ID"
            AttributeType: "S"
          # - AttributeName: Owner
          #   AttributeType: S
          # - AtrributeName: AllowedUsers
          #   AttributeType: SS
          # - AttributeName: AvailableDevices
          #   AttributeType: SS
        KeySchema:
          # - AttributeName: Name
          #   KeyType: HASH
          - AttributeName: "ID"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: FarmDynamoDbTable
    FarmUserDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "ID"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "ID"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: FarmUserDynamoDbTable
    FarmDevicesDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "ID"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "ID"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: FarmDevicesDynamoDbTable
